import sys
import os
from pathlib import Path

from PySide6.QtGui import QGuiApplication
from PySide6.QtQml import QQmlApplicationEngine
from PySide6.QtCore import QUrl

from Backend.LoginManager import LoginManager
from Backend.ScreenLoader import ScreenLoader
from Backend.ProjectManager import ProjectManager

def main():
    """
    Main entry point for the Project Manager application.
    Sets up the PySide6 QML application with the LoginManager backend.
    """

    print("Starting Project Manager application...")
    # Set QML style to Basic to allow full customization
    os.environ["QT_QUICK_CONTROLS_STYLE"] = "Basic"
    
    # Create the application
    app = QGuiApplication(sys.argv)
    app.setApplicationName("Project Manager")
    app.setOrganizationName("ProjectManager")
    
    # Create QML engine
    engine = QQmlApplicationEngine()

    # Create and expose the LoginManager to QML
    login_manager = LoginManager()
    screen_loader = ScreenLoader()
    project_manager = ProjectManager()

    engine.rootContext().setContextProperty("screenLoader", screen_loader)
    engine.rootContext().setContextProperty("loginManager", login_manager)
    engine.rootContext().setContextProperty("projectManager", project_manager)

    # Prefer loading QML from resources (qrc). If compiled resources module
    # isn't available, fall back to loading local files. To compile resources
    # run: `pyside6-rcc resources.qrc -o resources_rc.py` in the ProjectManagerV2 folder.
    try:
        import resources_rc  # generated by pyside6-rcc; registers qrc resources
        qml_url = QUrl("qrc:/main.qml")
    except Exception:
        qml_file = Path(__file__).parent / "main.qml"
        print("resources_rc not found; loading QML from local files.")
        print("To embed QML in resources run: pyside6-rcc resources.qrc -o resources_rc.py")
        qml_url = QUrl.fromLocalFile(str(qml_file))

    engine.load(qml_url)

    if not engine.rootObjects():
        print("Failed to load QML file.")
        sys.exit(-1)

    sys.exit(app.exec())

if __name__ == "__main__":
    main()